theme: jekyll-theme-hacker


plugins:
  - jekyll-seo-tag

# Using alternative using env in jekyl (docker): export PAGES_REPO_NWO=sohale/sohale.github.io
# repository: sohale/sohale.github.io

baseurl: ""

url: "https://sohale.github.io"

# To disable metadata plugin: e.g., repo links, GitHub-aware title handling, maintainer metadata, etc
# github: [false]

# timezone: Europe/London

title: "Sohail Siadatnejad, PhD"
description: "Sohail Siadatnejad's homepage"
show_downloads: false
# google_analytics: (Not working. Ignore)
# This would have been good, but GA has changed their snippet. Compare: https://github.com/pages-themes/hacker/blob/master/_includes/head-custom-google-analytics.html
# google_analytics: YOUR-ID
